### ISSUE TITLE
Is CLIP_SAMPLESHEET_TO_BARCODE CLIP-specific?

### ISSUE THREAD

**Issue by samirelanduk** [goodwright/flow-nf#17]
The module which creates an Ultraplex barcode file from an annotation sheet is currently called CLIP_SAMPLESHEET_TO_BARCODE. There doesn’t seem to be anything specific to CLIP in this in terms of the columns it uses.

Unless there’s something CLIP specific I’ve missed, could it be renamed to simply SAMPLESHEET_TO_BARCODE (or ANNOTATION_SHEET_TO_BARCODE if we’re sticking to the convention that sample sheet = what preprocessing pipelines take to describe already demultiplexes samples and annotation sheet = description of multiplexed file).

**Comment by CharlotteAnne** [comment]
I agree with your assessment! Again - would you like me to implement?

**Comment by CharlotteAnne** [comment]
Again, here ultraplex and the demultiplexing pipeline can theoretically demultiplex any type of sequencing data, just if you're working with very standard things like rna-seq or chip-seq the sequencing facility often perform this step for you.

**Comment by samirelanduk** [comment]
If it always looks for those three columns and produces a barcode file in the same way each time, I don't see why we would need different modules for different sample types - it's more Ultraplex-specific than sample type specific.

**Comment by CharlotteAnne** [comment]
if it needs to be extended in future it can be. so should i implement or you @samirelanduk ?

**Comment by samirelanduk** [comment]
Yes please make the change if we're agreed it's not CLIP-specific, cheers.
