### ISSUE TITLE
Annotation sheet column names

### ISSUE THREAD

**Issue by samirelanduk** [goodwright/flow-nf#18]
In CLIP_SAMPLESHEET_TO_BARCODE, the following column names are sought:

```python
five_prime = df_samplesheet["5prime_barcode"]
three_prime = df_samplesheet["3prime_barcode"]
sample_names = df_samplesheet["id"]
```

Unless it would break something else, could these be changed to '5' Barcode Sequence', '3' Barcode Sequence' and 'Sample Name' respectively?

**Comment by CharlotteAnne** [comment]
I think this is fine - do you want me to make the change?

**Comment by chris-cheshire** [comment]
Whats the reasoning? I hate spaces and caps so much in column names, its very triggering for me 😆. Is it for user readability or something?

**Comment by samirelanduk** [comment]
Normally I agree, but the annotation sheets are basically part of the user interface so they need to have as human readable a name as possible. The other columns which reference 5' or 3' all use "5'" and "3'" so it's also a bit inconsistent otherwise.

**Comment by CharlotteAnne** [comment]
So should I make the change or will you @samirelanduk

**Comment by samirelanduk** [comment]
Yeah if you could, cheers.
