### ISSUE TITLE
Can demultiplex pipeline take multiple annotation sheets?

### ISSUE THREAD

**Issue by samirelanduk** [goodwright/flow-nf#19]
The demultiplex pipeline currently takes a single annotation sheet, which is fine for almost all cases. Flow lanes can have multiple annotation sheets, where there is a mix of, say, CLIP and RNA-Seq samples in a single multiplexed reads file. What would the options be for allowing multiple annotation sheets as inputs?

Having an arbitrary number might be hard, but we could hardcode say, 5 (`--annotation`, `--annotation2` etc) of which only the first is required. The CLIP_SAMPLESHEET_TO_BARCODE module could then take multiple input CSVs and create a single barcode file (as the three columns that Ultraplex cares about would be in all annotation sheets).

Not super urgent, but will probably be required eventually.

**Comment by CharlotteAnne** [comment]
This seems very possible, I think also an arbitrary number wouldn't be difficult, --annotation can take a list as input and then only the necessary columns are taken forward from each csv and just concatenated. Will see where this fits in with mine and Chris' other tasks.

**Comment by CharlotteAnne** [comment]
Sometimes a lane of sequencing data can contain multiple data types - such as in ule lab they might combine quantseq and clipseq or riboseq on the same lane, so this would be useful. Ultraplex is flexible for really any kind of data demultiplexing so I really don't see this as CLIP-specific at all.

**Comment by samirelanduk** [comment]
Having a single param take a column-separated list of files would mean modifying Flow (currently it's one param, one file) - but maybe it could look for all params that being `annotation_n` and do something with that, if you do want to let it take an arbitrary number? Hardcoding a specific number such as 5 would require the fewest changes to the way Flow works.
